sudo: false
language: scala
dist: bionic
jdk:
- openjdk11
before_install:
- export CXX='g++-4.8'
- nvm install 10.13.0 && nvm use 10.13.0 && npm install
- wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py
  | python -c "import sys; main=lambda x,y:sys.stderr.write('Download failed\n');
  exec(sys.stdin.read()); main('~/calibre-bin', True)" >/dev/null
- export PATH="~/calibre-bin/calibre/:/home/travis/calibre-bin/calibre/:$PATH"
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
  - "$HOME/.sbt/launchers"
  - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
- sbt build epub
- git checkout .
- echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy.key\n"
  >> ~/.ssh/config
- git config --global user.email "6b656e6a69@gmail.com"
- git config --global user.name "xuwei-k"
- mv gitbook/_book ../
- mv book.epub ../_book/scala-protobuf-docs.epub
- git fetch origin gh-pages:gh-pages
- git clean -fdx
after_success:
- openssl aes-256-cbc -pass "pass:$SERVER_KEY" -pbkdf2 -in .travis/deploy_key.enc -d -a
  -out deploy.key
- cp deploy.key ~/.ssh/
- chmod 600 ~/.ssh/deploy.key
- git checkout gh-pages
- rm -rf ./*
- cp -r ../_book/* ./
- git add .
- git commit -a -m "auto commit on travis $TRAVIS_JOB_NUMBER $TRAVIS_COMMIT"
- if [[ "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_EVENT_TYPE}" == "push" && "${TRAVIS_REPO_SLUG}" == "xuwei-k/scala-protobuf-docs" ]];
  then git push git@github.com:xuwei-k/scala-protobuf-docs.git gh-pages:gh-pages ;
  fi
after_script:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
- find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
env:
  global:
    secure: GWyZROYa+DOQgndkALIvZhKsvLH63viYxBp/+i+Y1TNoAvEi01iIFNt5m6ZDpwIdsJIDhAQsxoQzpJWIl/wXElzBykuzxMM5NQjcMzxxkp5WmisZhFz4xt9LKiwcYELnLihMWbQLa4v75iZ3niZD37mxGUVwSlBqGQ0iETU7WVOMXZ4D/hZEwyzF5QR8tKliNbRjv9ThE7DK5K5/9TGhKkwZzSKlNIoiSLOLNeLUMLEN+cA6PqgZ2jizPnejIcME5C+CSJ8o3rAaZNT8LtiUiObEYpa1WcBQqSYZWnPc8ZBO686r4hKd0BcoRDljEqKjogANkCayIRV1EpgBBv43CLXN9n1/oKGb5+62vLoyDpzvJoPheNaZJ+L2uqs3VSqsj6iCgvCx6TsSGErZkXTrcha03y+td0/DR5f1v7orvu/9VXjM8hzzvrz11oa0RCUuunLHypdYdiX5UPejv7Hb5KrIXJVI6ErST+ruOHEsuueK5vLhFoNrldEMZPvPaHane9/BlVg7eGGAoBHvhzs5DyyvSwaUqOiAfKb3mXa3P9Y+8mZ2V2DGOcMYn4u11HT+3COvaMpfhbR65KbKln3A99+fARXYUg+ashvf5pyAVBtHnmapgWmomdbKlRwIZTLxuZzg0EbLCW9uLnIYcfK1kkChbsxQp6u+QErTprlvCwY=
